### PR TITLE
run test by npm test

### PR DESCRIPTION
**Pull request by sdf611097**
`npm test` will trigger pretest and then test.
After success of test, will run posttest.

By adding a simple express to start parse-server, and implementing a shutdown.
Before test, start local mongodb and parse-server.
Once test success, close the mongodb and parse-server.

I also close both when test failed.

### CODE REVIEW

**Comment by shiki** [comment]
Can we have the option to make this optional though? If you are actively working on a test, how would you observe the data changes? Would you have to run a different parse-server again?

**Comment by sdf611097** [comment]
**_Can we have the option to make this optional though?_**
Option for what?

**_how would you observe the data changes? _**
I add a test of mongodb, the test will pass. So the db data changed as my expected.

**_Would you have to run a different parse-server again?_**
Create another parse-server with different setting?

**Comment by sdf611097** [comment]
Hi shiki, 

I do not catch what you mean. 

The option you say is testing it on local or developer's server? We can add environment variables to specify the target server to do this. But I do not suggest testing on production server. Once a testcase delete all objects in a class or even drop db. It is a disaster. Or you must check each testcases carefully to avoid these things happen. 

How to observer local db? We can use [parse-dashboard](https://github.com/ParsePlatform/parse-dashboard) to see what the obj in db(parse format), or use mongodb cmd tool.

I think test different parse-server is ok. If you think test only one parse-server configuration is not enough. We can test 2 parse-server with different configuration to test this module can apply parse-server with url/mountPath and so on.

**Comment by shiki** [comment]
> Can we have the option to make this optional though?
> Option for what?

The option to use `npm test` or use the current testing method that is currently documented. 

I have two issues with this PR. 

1. I don't think we should have that `mongodb.test.js`. It's not really related to the purpose of this library.
2. I am getting a few errors when running `npm test`. What do you think these are? https://gist.github.com/shiki/c18a18ba473d49da5ef449c15c491778

**Comment by sdf611097** [comment]
Original test by makefile cannot test when local ParseServer is not running.
In out tests, we will delete something not created by our test. If delete something from the user's db, it will be a disaster. So I think we should start it automatically either by `npm test` or Makefile. Both way is OK, but I'm not familiar to write Makefile.

1.  I delete it.
2.  These errors message is showed by Parse-Server. Our test cases do try to using invalid request to expected it failed, and these cases will throw exception and print it out on  Parse-Server. I add comments on these tests.

**Pull request merged**
